### ISSUE TITLE
Bilder im Blockeditor unscharf

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/FAU-Einrichtungen#1584]
``` css
main figure.wp-block-image, main figure.wp-block-image img {
width: fit-content;
}
```

Bei der Umwandlung von alten Bildern in den Block-Editor werden diese Unscharf wegen CSS,
da

``` css
main figure.wp-block-image, main figure.wp-block-image img {
    max-width: 100%;
    /* width: 100%; */
    width: fit-content;
}
```

width auf 100% gesetzt hat, was dazu führt, dass auch kleinere Bildgrößen großgezogen werden.
Testen mit verschiedenen Bildgrößen
